before_script:
   - sudo apt-get -qq update
   - sudo apt-get install -qq build-essential libboost-all-dev git cmake libprotobuf-dev protobuf-compiler protobuf-c-compiler liblog4cxx10-dev

language: cpp
script:
 - mkdir build
 - cd build
 - cmake ..
 - make
 - ctest -E tuntap # exclude TUN/TAP test as this is not supported in Travis
 - sudo make install
