before_script:
   - sudo apt-get -qq update
   - sudo apt-get install -qq build-essential libboost-all-dev git cmake libprotobuf-dev protobuf-compiler protobuf-c-compiler openvpn liblog4cxx10-dev
   - sudo modprobe tun
   - sudo ./scripts/setup_tuntap.sh 10.0.0.1 tun0

language: cpp
script:
 - mkdir build
 - cd build
 - cmake ..
 - make
 - make test
 - sudo make install
